[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
futures = "0.3.28"
lazy_static = "1.5.0"
mongodb =  "3.0.1"
rocket = {version = "=0.5.0-rc.4", features = ["json"] }
serde = "1.0.188"
tokio = {version = "1.32.0", features = ["full"]}

